[features]
seeds = false
[programs.devnet]
currency_coin = "A3mhZsPAjroa8oQokfjGKNNNrKwbpz5ZwszHduYs6hz6"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/hedgehog/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
fetch-state = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/fetch-state.ts"
buy-bonds0 = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/buy-bonds0.ts"
sell-bonds0 = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/sell-bonds0.ts"
buy-bonds1 = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/buy-bonds1.ts"
redeem-bonds0 = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/redeem-bonds0.ts"
redeem-bonds1 = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/redeem-bonds1.ts"
crank0 = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/crank0.ts"
crank1 = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/crank1.ts"
crank3 = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/crank3.ts"
main = "yarn run ts-node app/main.ts"
