[features]
seeds = false
[programs.devnet]
currency_coin = "DbarUMKm62WkgTwiBTE9VykHL2yytNDpD4R2ypx1SHPu"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/hedgehog/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
